eureka:
  instance:
    prefer-ip-address: true
  client:
    healthcheck:
      enabled: true
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0

server:
  port: 8087

management:
  security:
    enabled: false