spring:
  application:
    name: registry
  cloud:
    config:
      uri: ${CONFIG_URL}
      fail-fast: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0

server:
  port: 8887

management:
  security:
    enabled: false