version: '2.1'
services:
  config:
    build: ./config-service
    ports:
          - 8888:8888
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888"]
      interval: 30s
      timeout: 10s
      retries: 5
    logging:
      options:
        max-size: "10m"
        max-file: "10"
  family-service:
    build: ./family-service
    restart: always
    depends_on:
      config:
        condition: service_healthy
    ports:
      - 8080:8080
    environment:
      CONFIG_URL: ${CONFIG_URL}
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    #  service-registry:
    #    build: ./service-registry
    #    restart: always
    #    logging:
    #      options:
    #        max-size: "10m"
    #        max-file: "10"
    #    ports:
    #      - 8887:8887
    #      - 8761:8761
    #    environment:
    #      CONFIG_URL: ${CONFIG_URL}
    #    links:
    #      - config
    #  gateway:
    #    build: ./gateway
    #    restart: always
    #    logging:
    #      options:
    #        max-size: "10m"
    #        max-file: "10"
    #    ports:
    #      - 8886:8886
    #    environment:
    #      CONFIG_URL: ${CONFIG_URL}
    #    links:
    #      - service-registry
    #      - config
