management:
  security:
    enabled: false


server:
  port: 8081

security:
    oauth2:
        resource:
            userInfoUri: http://${auth-server:localhost}:8000/auth/user
            preferTokenInfo: false
