server:
  port: 8886

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

  routes:
    family-service:
      path: /family/**
      serviceId: family-service
      stripPrefix: true
      sensitiveHeaders:
    news-service:
      path: /news/**
      serviceId: news-service
      stripPrefix: true
      sensitiveHeaders:


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000