server:
  port: 8886

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000
  routes:
    auth-service:
        path: /auth/**
        serviceId: auth-service
        stripPrefix: false
        sensitiveHeaders:
    family-service:
      path: /family/**
      serviceId: family-service
      stripPrefix: true
      sensitiveHeaders: Cookie,Set-Cookie
    news-service:
      path: /news/**
      serviceId: news-service
      stripPrefix: true
      sensitiveHeaders: Cookie,Set-Cookie


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
