server:
  port: 8886

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000
  sensitiveHeaders: Cookie,Set-Cookie
  routes:
    auth-service:
        path: /auth/**
        url: http://localhost:8000
        stripPrefix: false
        sensitiveHeaders:
    family-service:
      path: /family/**
      serviceId: family-service
      stripPrefix: true
    news-service:
      path: /news/**
      serviceId: news-service
      stripPrefix: true


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

security:
    oauth2:
        client:
            clientId: app
            clientSecret: secret
            accessTokenUri: http://auth-server:8000/auth/ouath/token
            clientAuthenticationScheme: form
            scope:
                - webclient
        resource:
            userInfoUri: http://auth-server:8000/auth/user
            preferTokenInfo: false