spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: ${AUTH_DB_URL:jdbc:postgresql://localhost:5432/auth}
    username: ${AUTH_DB_USER:postgres}
    password: ${AUTH_DB_PASSWORD:postgres}
